---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- include: ruby.yml
- include: puma.yml

- name: Update apt-get cache for correct work of jdauphant.nginx
  apt:
    update_cache: true
