---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
verifier:
  name: testinfra
  additional_files_or_dirs:
    - tests
