name: 'Ansible Lint'

on:
  - push
  - pull_request

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add mock vault file
        run: |
          - touch ansible/vault.key
      - name: lint
        uses: addnab/docker-run-action@v2
        with:
          image: quay.io/ansible/toolset:latest
          options: -v ${{ github.workspace }}/ansible:/app -w /app
          run: |
            ansible-lint
