name: 'Ansible Lint'

on:
  - push
  - pull_request

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: addnab/docker-run-action@v2
        with:
          registry: quay.io
          image: ansible/toolset:latest
          options: --rm -v ${PWD}/ansible:/app -w /app -it
          run: |
            ansible-lint
