name: 'Packer Validate'

on: push

jobs:
  packer-validate:
    strategy:
      matrix:
        packerfile:
          - app.json
          - db.json
          - immutable.json
          - ubuntu16.json
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ matrix.packerfile }}
      - name: validate file
        run: |
          packer validate -var-file=packer/variables.json.example packer/${{ matrix.packerfile }}
