name: 'Terraform Validate'

on: push

jobs:
  terraform-validate:
    strategy:
      matrix:
        environment:
          - prod
          - stage
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          terraform --version
      - uses: actions/checkout@v2
      - name: init terraform
        working-directory: terraform/${{ matrix.environment }}
        run: |
          terraform init -backend=false
      - name: validate
        working-directory: terraform/${{ matrix.environment }}
        run: |
          terraform validate
