name: 'tflint'

on:
  - push
  - pull_request

jobs:
  tflint:
    strategy:
      matrix:
        folder:
          - modules/app
          - modules/db
          - prod
          - stage
    runs-on: ubuntu-latest
    steps:
      - uses: terraform-linters/setup-tflint@v1
      - uses: actions/checkout@v2
      - name: lint
        working-directory: terraform/${{ matrix.environment }}
        run: |
          tflint
