name: 'Terraform Validate'

on: push

jobs:
  tflint:
    strategy:
      matrix:
        folder:
          - modules/app
          - modules/db
          - prod
          - stage
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.8
      - uses: actions/checkout@v2
      - name: lint
        working-directory: terraform/${{ matrix.environment }}
        run: |
          tflint
